name: EvolveRob
favicon: null
layout_spectrum: 0.8894
typography_spectrum: 0.75571
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
title: The evolution of a man as he lives his life
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-73087759-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#a5c6ef'
    - '#565455'
    - '#af986f'
    - '#17140f'
    - '#fef2c0'
  brandStrength: 0.7562182191759348
  lightness: 0.4065688904374838
  saturation: 0.1935755331069231
  rhythmicContrast: 0.2727577434852719
purpose: []
